version: "3.9"

services:
  laboralsalud_local:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laboralsalud_local
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
      ENV: ${ENV:-local}
      DEBUG: ${DEBUG:-True}
      GUNICORN_WSGI: ${GUNICORN_WSGI:-laboralsalud.wsgi_local:application}
      DB_HOST: ${DB_HOST:-mariadb_shared}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-lbls_local}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SECRET_KEY: ${SECRET_KEY}
      SESSION_COOKIE_NAME: ${SESSION_COOKIE_NAME:-laboral_session_local}
      SERVER_EMAIL: ${SERVER_EMAIL}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-2}
      GUNICORN_THREADS: ${GUNICORN_THREADS:-1}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-120}
      GUNICORN_BIND: ${GUNICORN_BIND:-0.0.0.0:8000}
      COLLECT_STATIC: ${COLLECT_STATIC:-true}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS:-true}
    volumes:
      - laboral_local_static:/app/static
      - laboral_local_media:/app/media
      - laboral_local_logs:/app/logs
    ports:
      - "8000:8000"
    networks:
      - dokploy-network
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.enable=true

  mariadb:
    image: mariadb:11
    container_name: mariadb_shared
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: piranha
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    ports:
      - "3306:3306"
    networks:
      - dokploy-network


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - dokploy-network

volumes:
  laboral_local_static:
    driver: local
  laboral_local_media:
    driver: local
  laboral_local_logs:
    driver: local
  mariadb_data:
    driver: local

networks:
  dokploy-network:
    external: true