version: "3.9"

services:
  laboralsalud_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laboralsalud_dev
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - laboral_dev_static:/app/static
      - laboral_dev_media:/app/media
      - laboral_dev_logs:/app/logs
    ports:
      - "8000:8000"
    networks:
      - dokploy-network
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.enable=true

volumes:
  laboral_dev_static:
    driver: local
  laboral_dev_media:
    driver: local
  laboral_dev_logs:
    driver: local

networks:
  dokploy-network:
    external: true