# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-10 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usu_profile',
            },
        ),
        migrations.CreateModel(
            name='UsuCategPermisos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, db_column='CATEGORIA', max_length=100, null=True)),
                ('orden', models.IntegerField(blank=True, db_column='ORDEN', null=True)),
            ],
            options={
                'db_table': 'usu_permiso_categ',
            },
        ),
        migrations.CreateModel(
            name='UsuPermiso',
            fields=[
                ('id_permiso', models.AutoField(db_column='ID_PERMISO', primary_key=True, serialize=False)),
                ('permiso', models.CharField(blank=True, db_column='PERMISO', max_length=100)),
                ('permiso_name', models.CharField(blank=True, db_column='PERMISO_NAME', max_length=100)),
                ('categoria', models.ForeignKey(blank=True, db_column='CATEGORIA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.UsuCategPermisos')),
            ],
            options={
                'db_table': 'usu_permiso',
            },
        ),
        migrations.CreateModel(
            name='UsuUsuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_USUARIO', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=200)),
                ('usuario', models.CharField(blank=True, db_column='USUARIO', max_length=100)),
                ('password', models.CharField(blank=True, db_column='PASSWORD', max_length=100)),
                ('tipoUsr', models.IntegerField(choices=[(0, 'Administrador'), (1, 'M\xe9dico/Profesional'), (2, 'Encargado')], default=0)),
                ('nro_doc', models.CharField(blank=True, max_length=50, null=True, verbose_name='N\xfamero')),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=100, verbose_name='E-Mail')),
                ('baja', models.BooleanField(default=False)),
                ('permisos', models.ManyToManyField(to='usuarios.UsuPermiso')),
            ],
            options={
                'db_table': 'usu_usuario',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.UsuUsuario'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
