# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuGrupo',
            fields=[
                ('id_grupo', models.IntegerField(db_column='ID_GRUPO', primary_key=True, serialize=False)),
                ('grupo', models.CharField(blank=True, db_column='GRUPO', max_length=50)),
            ],
            options={
                'db_table': 'usu_grupo',
            },
        ),
        migrations.AddField(
            model_name='usuusuario',
            name='grupo',
            field=models.ForeignKey(blank=True, db_column='GRUPO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.UsuGrupo'),
        ),
    ]
