# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0005_auto_20191108_0942'),
        ('usuarios', '0002_auto_20191023_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuusuario',
            name='grupo',
        ),
        migrations.AddField(
            model_name='usuusuario',
            name='empresas',
            field=models.ManyToManyField(to='entidades.ent_empresa'),
        ),
        migrations.AlterField(
            model_name='usuusuario',
            name='tipoUsr',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'M\xe9dico/Profesional'), (2, 'RRHH/Empresa')], default=0),
        ),
        migrations.DeleteModel(
            name='UsuGrupo',
        ),
    ]
