# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_auto_20191203_2000'),
        ('entidades', '0005_auto_20191108_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuracion',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cuit', models.CharField(max_length=50, verbose_name='CUIT')),
                ('iibb', models.CharField(blank=True, max_length=50, null=True, verbose_name='N\xba IIBB')),
                ('fecha_inicio_activ', models.DateField(null=True, verbose_name='Fecha Inicio Actividades')),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio/Ubicaci\xf3n')),
                ('datos_extra', models.CharField(blank=True, max_length=200, null=True, verbose_name='Datos Extra')),
                ('mail_cuerpo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cuerpo del Email (env\xedo de Ausentismos)')),
                ('mail_servidor', models.CharField(blank=True, max_length=100, verbose_name='Servidor SMTP')),
                ('mail_puerto', models.IntegerField(blank=True, default=587, null=True, verbose_name='Puerto')),
                ('mail_usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('mail_password', models.CharField(blank=True, max_length=100, verbose_name='Password')),
                ('ruta_logo', models.CharField(blank=True, db_column='ruta_logo', max_length=100, null=True, verbose_name='Ruta Logo')),
            ],
            options={
                'db_table': 'gral_empresa',
            },
        ),
        migrations.CreateModel(
            name='turnos',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha Turno')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora Turno')),
                ('detalle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Diagn\xf3stico')),
                ('estado', models.IntegerField(blank=True, choices=[(0, b'PENDIENTE'), (1, b'ATENDIDO'), (2, b'NO ASISTI\xc3\x93')], null=True, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('baja', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modif', models.DateField(auto_now=True)),
                ('empleado', models.ForeignKey(blank=True, db_column='empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno_empleado', to='entidades.ent_empleado', verbose_name='Empleado')),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno_empresa', to='entidades.ent_empresa', verbose_name='Empresa')),
                ('usuario_carga', models.ForeignKey(blank=True, db_column='usuario_carga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno_usuario_carga', to='usuarios.UsuUsuario')),
            ],
            options={
                'ordering': ['fecha', 'hora', 'estado'],
                'db_table': 'turnos',
            },
        ),
    ]
