# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_auto_20191105_1210'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno_empresa', to='entidades.ent_empresa', verbose_name='Empresa'),
        ),
    ]
