# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuracion',
            table='configuracion',
        ),
    ]
