# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-08 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_turnos_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnos',
            options={'ordering': ['-fecha', 'estado']},
        ),
    ]
