# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20191112_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='hora',
            field=models.DateField(blank=True, null=True, verbose_name='Hora Turno'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Turno'),
        ),
    ]
