# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-09 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20191203_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Turno'),
        ),
    ]
