# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20191209_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuracion',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cuit', models.CharField(max_length=50, verbose_name='CUIT')),
                ('iibb', models.CharField(blank=True, max_length=50, null=True, verbose_name='N\xba IIBB')),
                ('fecha_inicio_activ', models.DateTimeField(null=True, verbose_name='Fecha Inicio Actividades')),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio/Ubicaci\xf3n')),
                ('datos_extra', models.CharField(blank=True, max_length=200, null=True, verbose_name='Datos Extra')),
                ('mail_cuerpo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cuerpo del Email (env\xedo de Ausentismos)')),
                ('mail_servidor', models.CharField(blank=True, max_length=100, verbose_name='Servidor SMTP')),
                ('mail_puerto', models.IntegerField(blank=True, default=587, null=True, verbose_name='Puerto')),
                ('mail_usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('mail_password', models.CharField(blank=True, max_length=100, verbose_name='Password')),
                ('ruta_logo', models.CharField(blank=True, db_column='ruta_logo', max_length=100, null=True)),
            ],
            options={
                'db_table': 'gral_empresa',
            },
        ),
        migrations.AlterModelOptions(
            name='turnos',
            options={'ordering': ['fecha', 'hora', 'estado']},
        ),
        migrations.AlterField(
            model_name='turnos',
            name='detalle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diagn\xf3stico'),
        ),
    ]
