# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-05 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ent_art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='C\xf3digo')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre')),
                ('prestador', models.CharField(blank=True, max_length=500, null=True, verbose_name='Prestador')),
                ('auditor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Auditor')),
                ('contacto_nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre')),
                ('contacto_telfijo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tel.Fijo')),
                ('contacto_telcel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Celular')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('baja', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modif', models.DateTimeField(auto_now=True)),
                ('usuario_carga', models.ForeignKey(blank=True, db_column='usuario_carga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_usuario_carga', to='usuarios.UsuUsuario')),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'ent_art',
            },
        ),
        migrations.CreateModel(
            name='ent_cargo',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=200)),
                ('baja', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['cargo'],
                'db_table': 'ent_cargo',
            },
        ),
        migrations.CreateModel(
            name='ent_empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_doc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento')),
                ('legajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Legajo')),
                ('apellido_y_nombre', models.CharField(max_length=200, verbose_name='Apelido y Nombre')),
                ('fecha_nac', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio')),
                ('provincia', models.IntegerField(blank=True, choices=[(0, 'CABA'), (1, b'Buenos Aires'), (2, b'Catamarca'), (3, 'C\xf3rdoba'), (4, b'Corrientes'), (5, 'Entre R\xedos'), (6, b'Jujuy'), (7, b'Mendoza'), (8, b'La Rioja'), (9, b'Salta'), (10, b'San Juan'), (11, b'San Luis'), (12, b'Santa Fe'), (13, b'Santiago del Estero'), (14, 'Tucum\xe1n'), (16, b'Chaco'), (17, b'Chubut'), (18, b'Formosa'), (19, b'Misiones'), (20, 'Neuqu\xe9n'), (21, b'La Pampa'), (22, b'R\xc3\xado Negro'), (23, b'Santa Cruz'), (24, 'Tierra del Fuego/Ant\xe1rtida/Islas Malvinas')], default=12, null=True, verbose_name='Provincia')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad')),
                ('cod_postal', models.CharField(blank=True, max_length=50, null=True, verbose_name='CP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tel\xe9fono')),
                ('celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('empr_fingreso', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso')),
                ('trab_fingreso', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso')),
                ('trab_fbaja', models.DateField(blank=True, null=True, verbose_name='Fecha Baja')),
                ('trab_armas', models.CharField(default='N', max_length=1, verbose_name='\xbfPortaci\xf3n de Armas?')),
                ('trab_tareas_dif', models.CharField(default='N', max_length=1, verbose_name='\xbfTareas Diferentes?')),
                ('trab_preocupac', models.CharField(default='N', max_length=1, verbose_name='\xbfPreocupacional?')),
                ('trab_preocup_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha Preocupacional')),
                ('trab_preocup_conclus', models.TextField(blank=True, null=True, verbose_name='Conclusi\xf3n Preocupacional')),
                ('trab_factores_riesgo', models.TextField(blank=True, null=True, verbose_name='Factores de Riesgo a lo que est\xe1 Expuesto')),
                ('trab_tareas_dif_det', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n Tareas Diferentes')),
                ('trab_anteriores', models.TextField(blank=True, null=True, verbose_name='Trabajos Anteriores')),
                ('trab_antecedentes', models.TextField(blank=True, null=True, verbose_name='Antecedentes Patol\xf3gicos')),
                ('trab_accidentes', models.TextField(blank=True, null=True, verbose_name='Accidentes ART')),
                ('trab_vacunas', models.TextField(blank=True, null=True, verbose_name='Vacunas')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Otras Observaciones')),
                ('baja', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modif', models.DateTimeField(auto_now=True)),
                ('art', models.ForeignKey(blank=True, db_column='art', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empl_art', to='entidades.ent_art', verbose_name='ART')),
            ],
            options={
                'ordering': ['apellido_y_nombre', 'empresa', 'nro_doc'],
                'db_table': 'ent_empleado',
            },
        ),
        migrations.CreateModel(
            name='ent_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Raz\xf3n Social')),
                ('cuit', models.CharField(blank=True, max_length=50, null=True, verbose_name='CUIT')),
                ('categFiscal', models.IntegerField(blank=True, choices=[(1, b'IVA Responsable Inscripto'), (2, b'Responsable No Inscripto'), (3, b'IVA No Responsable'), (4, b'IVA Sujeto Exento'), (5, b'Consumidor Final'), (6, b'Monotributista'), (7, b'No Categorizado'), (8, b'Proveedor Exterior'), (9, b'Consumidor Exterior'), (10, b'IVA Liberado-Ley19.640'), (11, 'IVA RI \u2013 Ag. Percepci\xf3n'), (12, b'Eventual'), (13, b'Monotributista Social'), (14, b'Eventual Social')], null=True, verbose_name='Categor\xeda Fiscal')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='C\xf3digo')),
                ('iibb', models.CharField(blank=True, max_length=50, null=True, verbose_name='N\xba IIBB')),
                ('fecha_inicio_activ', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Actividades')),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio')),
                ('provincia', models.IntegerField(blank=True, choices=[(0, 'CABA'), (1, b'Buenos Aires'), (2, b'Catamarca'), (3, 'C\xf3rdoba'), (4, b'Corrientes'), (5, 'Entre R\xedos'), (6, b'Jujuy'), (7, b'Mendoza'), (8, b'La Rioja'), (9, b'Salta'), (10, b'San Juan'), (11, b'San Luis'), (12, b'Santa Fe'), (13, b'Santiago del Estero'), (14, 'Tucum\xe1n'), (16, b'Chaco'), (17, b'Chubut'), (18, b'Formosa'), (19, b'Misiones'), (20, 'Neuqu\xe9n'), (21, b'La Pampa'), (22, b'R\xc3\xado Negro'), (23, b'Santa Cruz'), (24, 'Tierra del Fuego/Ant\xe1rtida/Islas Malvinas')], default=12, null=True, verbose_name='Provincia')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad')),
                ('cod_postal', models.CharField(blank=True, max_length=50, null=True, verbose_name='CP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tel\xe9fono')),
                ('celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('baja', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modif', models.DateTimeField(auto_now=True)),
                ('rubro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rubro')),
                ('cant_empleados', models.IntegerField(blank=True, null=True, verbose_name='Cant.Empl.')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('contacto_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contacto_tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tel\xe9fono')),
            ],
            options={
                'ordering': ['razon_social', 'cuit'],
                'db_table': 'ent_empresa',
            },
        ),
        migrations.CreateModel(
            name='ent_empresa_agrupamiento',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('baja', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['descripcion'],
                'db_table': 'ent_empresa_agrupamiento',
            },
        ),
        migrations.CreateModel(
            name='ent_especialidad',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=200)),
                ('baja', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['especialidad'],
                'db_table': 'ent_especialidad',
            },
        ),
        migrations.CreateModel(
            name='ent_medico_prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_y_nombre', models.CharField(max_length=200, verbose_name='Apellido y Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='C\xf3digo')),
                ('cuit', models.CharField(blank=True, max_length=50, null=True, verbose_name='CUIT')),
                ('nro_doc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento')),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio')),
                ('provincia', models.IntegerField(blank=True, choices=[(0, 'CABA'), (1, b'Buenos Aires'), (2, b'Catamarca'), (3, 'C\xf3rdoba'), (4, b'Corrientes'), (5, 'Entre R\xedos'), (6, b'Jujuy'), (7, b'Mendoza'), (8, b'La Rioja'), (9, b'Salta'), (10, b'San Juan'), (11, b'San Luis'), (12, b'Santa Fe'), (13, b'Santiago del Estero'), (14, 'Tucum\xe1n'), (16, b'Chaco'), (17, b'Chubut'), (18, b'Formosa'), (19, b'Misiones'), (20, 'Neuqu\xe9n'), (21, b'La Pampa'), (22, b'R\xc3\xado Negro'), (23, b'Santa Cruz'), (24, 'Tierra del Fuego/Ant\xe1rtida/Islas Malvinas')], default=12, null=True, verbose_name='Provincia')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad')),
                ('cod_postal', models.CharField(blank=True, max_length=50, null=True, verbose_name='CP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tel\xe9fono')),
                ('celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('baja', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modif', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(blank=True, db_column='especialidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='med_especialidad', to='entidades.ent_especialidad')),
                ('usuario_carga', models.ForeignKey(blank=True, db_column='usuario_carga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='med_usuario_carga', to='usuarios.UsuUsuario')),
            ],
            options={
                'ordering': ['apellido_y_nombre', 'codigo'],
                'db_table': 'ent_medico_prof',
            },
        ),

        migrations.AddField(
            model_name='ent_empresa',
            name='art',
            field=models.ForeignKey(blank=True, db_column='art', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empr_art', to='entidades.ent_art', verbose_name='ART'),
        ),
        migrations.AddField(
            model_name='ent_empresa',
            name='casa_central',
            field=models.ForeignKey(blank=True, db_column='casa_central', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empr_casa_central', to='entidades.ent_empresa', verbose_name='Casa Central'),
        ),
        migrations.AddField(
            model_name='ent_empresa',
            name='contacto_cargo',
            field=models.ForeignKey(blank=True, db_column='cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empr_cargo', to='entidades.ent_cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='ent_empresa',
            name='contacto_profesion',
            field=models.ForeignKey(blank=True, db_column='especialidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empr_especialidad', to='entidades.ent_especialidad', verbose_name='Profesi\xf3n'),
        ),
        migrations.AddField(
            model_name='ent_empresa',
            name='medico_prof',
            field=models.ForeignKey(blank=True, db_column='medico_prof', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empr_medico_prof', to='entidades.ent_medico_prof', verbose_name='M\xe9dico/Prof.'),
        ),
        migrations.AddField(
            model_name='ent_empresa',
            name='usuario_carga',
            field=models.ForeignKey(blank=True, db_column='usuario_carga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empr_usuario_carga', to='usuarios.UsuUsuario'),
        ),
        migrations.AddField(
            model_name='ent_empleado',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empl_empresa', to='entidades.ent_empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='ent_empleado',
            name='trab_cargo',
            field=models.ForeignKey(blank=True, db_column='cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empl_cargo', to='entidades.ent_cargo', verbose_name='Puesto de Trabajo'),
        ),
        migrations.AddField(
            model_name='ent_empleado',
            name='usuario_carga',
            field=models.ForeignKey(blank=True, db_column='usuario_carga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empl_usuario_carga', to='usuarios.UsuUsuario'),
        ),
    ]
