# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-05 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ent_empresa',
            name='agrupamiento',
            field=models.ForeignKey(blank=True, db_column='agrupamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empr_agrupamiento', to='entidades.ent_empresa_agrupamiento', verbose_name='Agrupamiento Empresa'),
        ),
    ]
