# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-04 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ent_empresa',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='ent_medico_prof',
            name='tipo_entidad',
        ),
        migrations.AddField(
            model_name='ent_empresa',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='ent_art',
            name='auditor',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Auditor'),
        ),
        migrations.AlterField(
            model_name='ent_art',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ent_art',
            name='contacto_telcel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='ent_art',
            name='contacto_telfijo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tel.Fijo'),
        ),
        migrations.AlterField(
            model_name='ent_art',
            name='nombre',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ent_art',
            name='prestador',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Prestador'),
        ),
    ]
