# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ent_empleado',
            name='trab_armas',
            field=models.CharField(default='N', max_length=1, verbose_name='\xbfPortaci\xf3n de Armas?'),
        ),
        migrations.AlterField(
            model_name='ent_empleado',
            name='trab_preocupac',
            field=models.CharField(default='N', max_length=1, verbose_name='\xbfPreocupacional?'),
        ),
    ]
