# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-30 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = []

    operations = [
    migrations.CreateModel(
            name='ent_empresa_agrupamiento',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('baja', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['descripcion'],
                'db_table': 'ent_empresa_agrupamiento',
            },
        ),
        migrations.AddField(
            model_name='ent_empresa',
            name='agrupamiento',
            field=models.ForeignKey(blank=True, db_column='agrupamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empr_agrupamiento', to='entidades.ent_empresa_agrupamiento', verbose_name='Agrupamiento Empresa'),
        ),
    ]
