# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-04 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_auto_20191004_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ent_empresa',
            name='art',
            field=models.ForeignKey(blank=True, db_column='art', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empr_art', to='entidades.ent_art', verbose_name='ART'),
        ),
        migrations.AlterField(
            model_name='ent_empresa',
            name='cant_empleados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cant.Empl.'),
        ),
        migrations.AlterField(
            model_name='ent_empresa',
            name='casa_central',
            field=models.ForeignKey(blank=True, db_column='casa_central', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empr_casa_central', to='entidades.ent_empresa', verbose_name='Casa Central'),
        ),
        migrations.AlterField(
            model_name='ent_empresa',
            name='contacto_cargo',
            field=models.ForeignKey(blank=True, db_column='cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empr_cargo', to='entidades.ent_cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='ent_empresa',
            name='contacto_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ent_empresa',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ent_empresa',
            name='contacto_profesion',
            field=models.ForeignKey(blank=True, db_column='especialidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empr_especialidad', to='entidades.ent_especialidad', verbose_name='Profesi\xf3n'),
        ),
        migrations.AlterField(
            model_name='ent_empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ent_empresa',
            name='fecha_inicio_activ',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio Actividades'),
        ),
        migrations.AlterField(
            model_name='ent_empresa',
            name='medico_prof',
            field=models.ForeignKey(blank=True, db_column='medico_prof', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empr_medico_prof', to='entidades.ent_medico_prof', verbose_name='M\xe9dico/Prof.'),
        ),
    ]
