# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_auto_20191011_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='ent_empleado',
            name='trab_tareas_dif_det',
            field=models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n Tareas Diferentes'),
        ),
        migrations.AlterField(
            model_name='ent_empleado',
            name='trab_tareas_dif',
            field=models.CharField(default='N', max_length=1, verbose_name='\xbfTareas Diferentes?'),
        ),
    ]
