# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_auto_20191011_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ent_empleado',
            name='trab_preocup_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Preocupacional'),
        ),
    ]
