# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-04 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_auto_20191004_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ent_empresa',
            name='fecha_inicio_activ',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Actividades'),
        ),
    ]
