# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-04 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_auto_20191004_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ent_empleado',
            options={'ordering': ['apellido_y_nombre']},
        ),
        migrations.RemoveField(
            model_name='ent_empleado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='ent_empleado',
            name='nombre',
        ),
        migrations.AddField(
            model_name='ent_empleado',
            name='apellido_y_nombre',
            field=models.CharField(default='', max_length=200, verbose_name='Apelido y Nombre'),
            preserve_default=False,
        ),
    ]
