# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0005_auto_20191004_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ent_empleado',
            name='art',
            field=models.ForeignKey(blank=True, db_column='art', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empl_art', to='entidades.ent_art', verbose_name='ART'),
        ),
        migrations.AlterField(
            model_name='ent_empleado',
            name='empr_fingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='ent_empleado',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empl_empresa', to='entidades.ent_empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='ent_empleado',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='ent_empleado',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Otras Observaciones'),
        ),
        migrations.AlterField(
            model_name='ent_empleado',
            name='trab_armas',
            field=models.BooleanField(default=False, verbose_name='\xbfPortaci\xf3n de Armas?'),
        ),
        migrations.AlterField(
            model_name='ent_empleado',
            name='trab_cargo',
            field=models.ForeignKey(blank=True, db_column='cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empl_cargo', to='entidades.ent_cargo', verbose_name='Puesto de Trabajo'),
        ),
        migrations.AlterField(
            model_name='ent_empleado',
            name='trab_fbaja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Baja'),
        ),
        migrations.AlterField(
            model_name='ent_empleado',
            name='trab_fingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='ent_empleado',
            name='trab_preocup_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Preocup.'),
        ),
        migrations.AlterField(
            model_name='ent_empleado',
            name='trab_preocupac',
            field=models.BooleanField(default=False, verbose_name='\xbfPreocupacional?'),
        ),
    ]
