# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0006_auto_20191009_1307'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ausentismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ausentismo', models.IntegerField(blank=True, choices=[(1, b'Inculpable'), (2, b'Accidente'), (3, b'Enfermedad')], default=12, null=True, verbose_name='Ausentismo')),
                ('aus_control', models.BooleanField(default=False, verbose_name='\xbfAsisti\xf3 a Control?')),
                ('aus_fcontrol', models.DateField(blank=True, null=True, verbose_name='Fecha Control')),
                ('aus_certificado', models.BooleanField(default=False, verbose_name='\xbfPresenta Certificado?')),
                ('aus_fcertif', models.DateField(blank=True, null=True, verbose_name='Fecha Certificado')),
                ('aus_fentrega_certif', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega Certif.')),
                ('aus_fcrondesde', models.DateField(blank=True, null=True, verbose_name='Cronol\xf3gica Desde')),
                ('aus_fcronhasta', models.DateField(blank=True, null=True, verbose_name='Cronol\xf3gica Hasta')),
                ('aus_diascaidos', models.IntegerField(blank=True, null=True, verbose_name='D\xedas Ca\xeddos')),
                ('aus_diasjustif', models.IntegerField(blank=True, null=True, verbose_name='D\xedas Justif.')),
                ('aus_freintegro', models.DateField(blank=True, null=True, verbose_name='Reintegro')),
                ('aus_falta', models.DateField(blank=True, null=True, verbose_name='Fecha Alta')),
                ('aus_tipo_alta', models.IntegerField(blank=True, choices=[(1, b'Definitiva'), (2, 'Con Restricci\xf3n')], null=True, verbose_name='Tipo Alta')),
                ('aus_frevision', models.DateField(blank=True, null=True, verbose_name='Fecha Revisi\xf3n')),
                ('aus_grupop', models.CharField(blank=True, max_length=200, null=True, verbose_name='Grupo Patol\xf3gico')),
                ('aus_diagn', models.TextField(blank=True, null=True, verbose_name='Diagn\xf3stico')),
                ('art_tipo_accidente', models.IntegerField(blank=True, choices=[(1, b'En Puesto de Trabajo'), (2, 'In It\xednere')], null=True, verbose_name='Tipo Alta')),
                ('art_ndenuncia', models.CharField(blank=True, max_length=50, null=True, verbose_name='N\xba Denuncia')),
                ('art_fcontrol', models.DateField(blank=True, null=True, verbose_name='Fecha Control')),
                ('art_faccidente', models.DateField(blank=True, null=True, verbose_name='Fecha Accidente')),
                ('art_fdenuncia', models.DateField(blank=True, null=True, verbose_name='Fecha Denuncia')),
                ('art_fcrondesde', models.DateField(blank=True, null=True, verbose_name='Cronol\xf3gica Desde')),
                ('art_fcronhasta', models.DateField(blank=True, null=True, verbose_name='Cronol\xf3gica Hasta')),
                ('art_diascaidos', models.IntegerField(blank=True, null=True, verbose_name='D\xedas Ca\xeddos')),
                ('art_freintegro', models.DateField(blank=True, null=True, verbose_name='Reintegro')),
                ('art_falta', models.DateField(blank=True, null=True, verbose_name='Fecha Alta')),
                ('art_tipo_alta', models.IntegerField(blank=True, choices=[(1, b'Definitiva'), (2, 'Con Restricci\xf3n')], null=True, verbose_name='Tipo Alta')),
                ('art_frevision', models.DateField(blank=True, null=True, verbose_name='Fecha Revisi\xf3n')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('descr_altaparc', models.TextField(blank=True, null=True, verbose_name='Descr.Alta Parcial')),
                ('detalle_acc_art', models.TextField(blank=True, null=True, verbose_name='Detalle Acc.ART')),
                ('estudios_partic', models.TextField(blank=True, null=True, verbose_name='Estudios Particulares')),
                ('estudios_art', models.TextField(blank=True, null=True, verbose_name='Estudios ART')),
                ('recalificac_art', models.TextField(blank=True, null=True, verbose_name='Recalificaci\xf3n ART')),
                ('baja', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modif', models.DateTimeField(auto_now=True)),
                ('art_medico', models.ForeignKey(blank=True, db_column='art_medico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_medico', to='entidades.ent_medico_prof', verbose_name='M\xe9dico ART')),
                ('aus_medico', models.ForeignKey(blank=True, db_column='aus_medico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aus_medico', to='entidades.ent_medico_prof', verbose_name='M\xe9dico Tratante')),
                ('empleado', models.ForeignKey(blank=True, db_column='empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aus_empleado', to='entidades.ent_empleado', verbose_name='Empleado')),
                ('usuario_carga', models.ForeignKey(blank=True, db_column='usuario_carga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aus_usuario_carga', to='usuarios.UsuUsuario')),
            ],
            options={
                'ordering': ['empleado'],
                'db_table': 'ausentismo',
            },
        ),
    ]
