# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-14 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausentismo',
            name='plan_accion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
