# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-14 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '__first__'),
        ('ausentismos', '0002_ausentismo_plan_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ausentismo_controles_patologias',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, max_length=1000, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modif', models.DateField(auto_now=True)),
                ('ausentismo', models.ForeignKey(blank=True, db_column='ausentismo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_ausentismo_pat', to='ausentismos.ausentismo')),
                ('usuario_carga', models.ForeignKey(blank=True, db_column='usuario_carga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_pat_usuario_carga', to='usuarios.UsuUsuario')),
            ],
            options={
                'ordering': ['fecha', 'id'],
                'db_table': 'ausentismo_controles_patologias',
            },
        ),
    ]
