# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismos', '0003_auto_20191014_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='aus_diagnostico',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=200)),
                ('diagnostico', models.CharField(max_length=200)),
                ('baja', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'aus_diagnostico',
            },
        ),
        migrations.CreateModel(
            name='aus_patologia',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=200)),
                ('patologia', models.CharField(max_length=200)),
                ('baja', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'aus_patologia',
            },
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='art_tipo_accidente',
            field=models.IntegerField(blank=True, choices=[(1, b'En Puesto de Trabajo'), (2, 'In It\xednere')], null=True, verbose_name='Tipo Accidente/Enfermedad'),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='aus_diagn',
            field=models.ForeignKey(blank=True, db_column='aus_diagn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aus_diagn', to='ausentismos.aus_diagnostico', verbose_name='Diagn\xf3stico'),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='aus_grupop',
            field=models.ForeignKey(blank=True, db_column='aus_grupop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aus_grupop', to='ausentismos.aus_patologia', verbose_name='Grupo Patol\xf3gico'),
        ),
    ]
