# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-30 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismos', '0003_ausentismo_controles_patologias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausentismo',
            name='tipo_ausentismo',
            field=models.IntegerField(blank=True, choices=[(1, b'Inculpable'), (3, b'Enfermedad Profesional'), (2, b'Accidente Denunciado'), (7, b'Accidente No Denunciado'), (4, b'Familiar Enfermo'), (5, b'Licencias Especiales'), (6, b'Embarazo')], null=True, verbose_name='Ausentismo'),
        ),
    ]
