# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismos', '0004_auto_20191018_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausentismo',
            options={'ordering': ['-fecha_creacion', 'empleado__empresa']},
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='fecha_modif',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='tipo_ausentismo',
            field=models.IntegerField(blank=True, choices=[(1, b'Inculpable'), (2, b'Accidente'), (3, b'Enfermedad Profesional')], null=True, verbose_name='Ausentismo'),
        ),
    ]
