# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismos', '0006_auto_20191108_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausentismo',
            name='art_freintegro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Reintegro'),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='art_frevision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Pr\xf3x.Control'),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='art_tipo_accidente',
            field=models.IntegerField(blank=True, choices=[(1, 'En Ocasi\xf3n de Trabajo'), (2, 'In It\xednere')], null=True, verbose_name='Tipo Accidente/Enfermedad'),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='aus_frevision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Pr\xf3x.Control'),
        ),
    ]
