# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismos', '0007_auto_20191203_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausentismo',
            name='tipo_control',
            field=models.IntegerField(blank=True, choices=[(1, b'Consultorio'), (2, b'A Domicilio')], null=True, verbose_name='Tipo Control'),
        ),
    ]
