# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-03 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismos', '0008_ausentismo_tipo_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausentismo',
            name='tipo_control',
            field=models.CharField(blank=True, choices=[(b'C', b'Consultorio'), (b'D', b'Domicilio')], max_length=1, null=True, verbose_name='Tipo Control'),
        ),
    ]
