# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismos', '0010_ausentismo_controles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausentismo',
            options={'ordering': ['-aus_fcrondesde', '-aus_fcronhasta', 'empleado__empresa']},
        ),
        migrations.RemoveField(
            model_name='ausentismo',
            name='art_diascaidos',
        ),
        migrations.RemoveField(
            model_name='ausentismo',
            name='art_falta',
        ),
        migrations.RemoveField(
            model_name='ausentismo',
            name='art_fcontrol',
        ),
        migrations.RemoveField(
            model_name='ausentismo',
            name='art_fcrondesde',
        ),
        migrations.RemoveField(
            model_name='ausentismo',
            name='art_fcronhasta',
        ),
        migrations.RemoveField(
            model_name='ausentismo',
            name='art_freintegro',
        ),
        migrations.RemoveField(
            model_name='ausentismo',
            name='art_frevision',
        ),
        migrations.RemoveField(
            model_name='ausentismo',
            name='art_medico',
        ),
        migrations.RemoveField(
            model_name='ausentismo',
            name='art_tipo_alta',
        ),
        migrations.RemoveField(
            model_name='ausentismo',
            name='aus_frevision',
        ),
        migrations.AlterField(
            model_name='aus_diagnostico',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aus_patologia',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='aus_diasjustif',
            field=models.IntegerField(blank=True, null=True, verbose_name='D\xedas Justificados'),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='aus_fcontrol',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Pr\xf3x.Control'),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='aus_freintegro',
            field=models.DateField(blank=True, null=True, verbose_name='F.Reintegro'),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='aus_medico',
            field=models.ForeignKey(blank=True, db_column='aus_medico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aus_medico', to='entidades.ent_medico_prof', verbose_name='M\xe9dico Tratante/ART'),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='aus_tipo_alta',
            field=models.IntegerField(blank=True, choices=[(0, b'En Curso'), (1, b'Definitiva'), (2, 'Con Restricci\xf3n')], null=True, verbose_name='Tipo Alta'),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='empleado',
            field=models.ForeignKey(blank=True, db_column='empleado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aus_empleado', to='entidades.ent_empleado', verbose_name='Empleado'),
        ),
    ]
