name: Deploy via Git Pull and Restart Server on OpalStack
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Connect to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/apps/lblsl_prueba2/laboralsalud
            git pull
            cd ..
            source lblsl_env/bin/activate 
            python laboralsalud/manage.py collectstatic --noinput
            apache2/bin/apachectl restart
            
